### ISSUE TITLE
Higher priority for replica set primary than secondaries?

### ISSUE THREAD

**Issue by fancyremarker** [aptible/docker-mongodb#21]
cc: @krallin 

(This is a question, not a prescription.) Right now, we use the same priority (`1`) for all members of a replica set. This means that, given a cluster with primary `mongo-1` and secondaries `mongo-2` and `mongo-3`, and the scenario:

1. `mongo-1` crashes.
2. `mongo-2` is elected new primary.
3. `mongo-1` is restored.

`mongo-2` will remain primary. We can, however, coerce `mongo-1` into reclaiming primary status whenever it's online by using priority `1` for primaries and `0.5` for secondaries.

A pro of this configuration is that the database container reported as primary in our system is much more likely to _actually_ be the primary (assuming it's up and running). Are there cons?

**Comment by krallin** [comment]
Summarizing our Slack conversation about this here for the record:

- The UI does not actually suggest the first node is the primary. It just says other nodes are in the same cluster (this is intentional: for replication, it does say that the first node is the master). We can of course always reword to make this even clearer if needed :smile:.
- There is a real downside to doing this since it'll trigger cluster re-elections than are not actually needed (which, among other things, will cause the master to close all open connections — which Mongo's doc refer to as a "maintenance window"). It might even cause *multiple* elections to get the node with the highest priority to become the master (according to the MongoDB docs).
- MongoDB clients actually discover the master on their own, so they don't need to be deliberately pointed at the primary. However, this only happens if you instruct them that they're connecting to a replica set, either by specifying multiple node names, or by specifying the replica set name. In practice, if you don't do that, then the client will behave just as if you were connecting to a standalone. When we make MongoDB clustering self-service, we should add a notice instructing users to properly configure their client.
- Customers that do care about having priorities can actually set them on their own.

So, the bottom line is, this doesn't seem like something we should be doing.

Let me know if I missed anything, @fancyremarker!

Cheers,
